image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

reinstall:
  stage: build
  artifacts:
    paths:
      - builds/sintyx/discord-bot/
  script:
    - pm2 stop app
    - git pull origin master
    - npm update

deploy:
  stage: deploy
  artifacts:
    paths:
      - builds/sintyx/discord-bot/
  script:
    - pm2 start app
