image: node:latest

stages:
  - deploy

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - cat my_private_key | base64 -W0
  - "which ssh-agent || ( apt-get install -qq openssh-client )"
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host */n/tStrictHostKeyChecking no/n/n" > ~/.ssh/config'

deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: http://158.69.218.138/
  script:
    - ssh root@158.69.218.138 "cd /home/ && ls"
