image: node:latest

stages:
  - first
  - build

testing:
  stage: first
  script:
    - sudo ls /home/node/

reinstall:
  stage: build
  script:
    - pm2 stop app
    - git pull origin master
    - npm update
    - pm2 start app
